services:
  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: pgWithNest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "listen_addresses=0.0.0.0"]
  #docker compose up db
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=pgWithNest
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
#docker compose up pgadmin


volumes:
  pgdata:
